name: ReActions
main: fromgate.reactions.ReActions
version: 0.0.1
website: http://www.minecraft-mccity.ru
author: fromgate, fromgate@gmail.com
softdepend: [Vault,Towny]
commands:
   react:
      aliases: [ra,rea,rct]
      description: 
      usage: 
           /react help